/**
 * Sandbox
 * This is a sample.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Errors', 'model/ReadUser', 'model/ReadUsers', 'model/WriteUser', 'api/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Error'), require('./model/Errors'), require('./model/ReadUser'), require('./model/ReadUsers'), require('./model/WriteUser'), require('./api/UsersApi'));
  }
}(function(ApiClient, Error, Errors, ReadUser, ReadUsers, WriteUser, UsersApi) {
  'use strict';

  /**
   * This_is_a_sample_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Sandbox = require('index'); // See note below*.
   * var xxxSvc = new Sandbox.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Sandbox.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Sandbox.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Sandbox.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The Errors model constructor.
     * @property {module:model/Errors}
     */
    Errors: Errors,
    /**
     * The ReadUser model constructor.
     * @property {module:model/ReadUser}
     */
    ReadUser: ReadUser,
    /**
     * The ReadUsers model constructor.
     * @property {module:model/ReadUsers}
     */
    ReadUsers: ReadUsers,
    /**
     * The WriteUser model constructor.
     * @property {module:model/WriteUser}
     */
    WriteUser: WriteUser,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
