/**
 * Sandbox
 * This is a sample.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Error from './Error';





/**
* The Errors model module.
* @module model/Errors
* @version 1.0.0
*/
export default class Errors {
    /**
    * Constructs a new <code>Errors</code>.
    * @alias module:model/Errors
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Errors</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Errors} obj Optional instance to populate.
    * @return {module:model/Errors} The populated <code>Errors</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Errors();

            
            
            

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Error>} errors
    */
    errors = undefined;








}


