/**
 * Sandbox
 * This is a sample.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ReadUser model module.
* @module model/ReadUser
* @version 1.0.0
*/
export default class ReadUser {
    /**
    * Constructs a new <code>ReadUser</code>.
    * @alias module:model/ReadUser
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ReadUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReadUser} obj Optional instance to populate.
    * @return {module:model/ReadUser} The populated <code>ReadUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReadUser();

            
            
            

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} user_id
    */
    user_id = undefined;
    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} email
    */
    email = undefined;








}


