/**
 * Sandbox
 * This is a sample.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ReadUser from './ReadUser';





/**
* The ReadUsers model module.
* @module model/ReadUsers
* @version 1.0.0
*/
export default class ReadUsers {
    /**
    * Constructs a new <code>ReadUsers</code>.
    * @alias module:model/ReadUsers
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ReadUsers</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ReadUsers} obj Optional instance to populate.
    * @return {module:model/ReadUsers} The populated <code>ReadUsers</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReadUsers();

            
            
            

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [ReadUser]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ReadUser>} users
    */
    users = undefined;








}


