/**
 * Sandbox
 * This is a sample.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WriteUser model module.
* @module model/WriteUser
* @version 1.0.0
*/
export default class WriteUser {
    /**
    * Constructs a new <code>WriteUser</code>.
    * @alias module:model/WriteUser
    * @class
    * @param username {String} 
    * @param email {String} 
    */

    constructor(username, email) {
        

        
        

        this['username'] = username;this['email'] = email;

        
    }

    /**
    * Constructs a <code>WriteUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WriteUser} obj Optional instance to populate.
    * @return {module:model/WriteUser} The populated <code>WriteUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WriteUser();

            
            
            

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} email
    */
    email = undefined;








}


